# These are supported funding model platforms

github: [kyranet, favna]
patreon: kyranet
open_collective: # Replace with a single Open Collective username
ko_fi: kyranet
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: ['https://donate.skyra.pw/paypal', 'https://donate.favware.tech/paypal']
